### ISSUE TITLE
Proposal: get rid x32 wheels

### ISSUE THREAD

**Issue by menshikh-iv** [RaRe-Technologies/gensim-wheels#5]
## Idea

I propose to remove `x32` wheel building. IMO this just spends time and rarely used now (we are in 2020, who still using `x32`? This is my personal assumtion)

**Pros:**
- Twice faster build (because of twice fewer jobs) -> twice fast release (wheel building + testing are the slowest part, @mpenkov can confirm)
- No x32-related hacks (typical lack of RAM on some tests)

**Cons:**
- x32 users affected (and we don't know how much, idk ways to evaluate them)

## Examples of other libraries

**Doesn't build x32**:
- spacy https://pypi.org/project/spacy/2.2.4/#files
- pytorch https://download.pytorch.org/whl/torch_stable.html, https://pypi.org/project/torch/1.5.0/#files
- tensorflow https://pypi.org/project/tensorflow/2.1.0/#files

**Still build x32**:
- numpy/scipy https://pypi.org/project/numpy/1.18.4/#files
- pandas https://pypi.org/project/pandas/1.0.3/#files
- sklearn https://pypi.org/project/scikit-learn/0.22.2.post1/#files

@mpenkov @piskvorky thoughts?

**Comment by piskvorky** [comment]
I'm in favour of removing x32. I didn't even know we had it.

IMO, the only relevant wheels are for (modern) Windows. All other installations can either compile themselves easily (unix), or expect pain anyway (ancient systems).

And if Windows wheels give us too much trouble, we could drop even that. I'd prefer not to, but it's conceivable. Gensim is open source and we cannot afford the project to become too annoying/costly to us.
