### ISSUE TITLE
unrecognized command line option '-std=c++14' during Linux builds

### ISSUE THREAD

**Issue by mpenkov** [RaRe-Technologies/gensim-wheels#9]
[full log](https://travis-ci.org/github/RaRe-Technologies/gensim-wheels/jobs/741064653)

I updated the Ubuntu distro to Bionic (18.04LTS) to get a newer compiler, and verified that the gcc version is recent enough:

```
$ x86_64-linux-gnu-gcc --version
x86_64-linux-gnu-gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

This is consistent with what TravisCI lists on their [page for Bionic](https://docs.travis-ci.com/user/reference/bionic/#compilers-and-build-toolchain), so no surprises there. According to the [GCC docs](https://gcc.gnu.org/onlinedocs/gcc-7.5.0/gcc/C-Dialect-Options.html#C-Dialect-Options), that version of the compiler _should_ support `-std=c++14`, so I'm not sure what the problem is here.

**Comment by piskvorky** [comment]
How about 20.04 LTS = Focal?

**Comment by mpenkov** [comment]
Tried it, unfortunately no effect.

https://travis-ci.org/github/RaRe-Technologies/gensim-wheels/jobs/741274157

**Comment by mpenkov** [comment]
```
Operating System Details

Distributor ID:	Ubuntu

Description:	Ubuntu 20.04.1 LTS

Release:	20.04

Codename:	focal

Systemd Version

systemd 245 (245.4-4ubuntu3)

Cookbooks Version

883ec55 https://github.com/travis-ci/travis-cookbooks/tree/883ec55

git version

git version 2.29.2

bash version

GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

gcc version

gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
```

**Comment by mpenkov** [comment]
I'm a bit stumped on how to proceed here, so opened https://github.com/spotify/annoy/issues/516

**Comment by piskvorky** [comment]
Weird. Is it just Annoy that errors out (not part of Gensim proper), or something truly blocking?

**Comment by mpenkov** [comment]
I think it's just Annoy. If we could exclude it from the build process somehow, then we may be able to proceed.

I also think I've found the cause of the problem. The build is running inside yet another Docker container, inside Travis, and that Docker container is running Trusty, which has the old gcc. Argh.

https://github.com/matthew-brett/multibuild/blob/da36cd5408e03cad504217de4a21bb8f19f2fb2f/travis_linux_steps.sh

I'm unfamiliar with this multibuild stuff, so my next step is to figure out who introduced it and go nag them. Failing that, I'll have to learn more about it.

**Comment by piskvorky** [comment]
We may have to move away from Travis altogether, I heard they're sunsetting their open source plans. So I'm not sure whether to invest more time into it.

"Github Actions" is one possible replacement – we have a ticket at https://github.com/RaRe-Technologies/gensim/issues/2696.

**Comment by mpenkov** [comment]
Yes, I've used github actions before, they are quite good.

The problem is: we're coupled to travis via this multibuild stuff, and breaking this coupling will require some effort.

**Comment by piskvorky** [comment]
That is true.

I see that effort as a great opportunity to clean up the CI system overall, make it saner – Travis is giving us too much trouble, unreliable. I look forward to it but not sure about the timing :) Certainly not now, in the middle of a release.

**Comment by mpenkov** [comment]
Yeah, while we're at it, we should consider building wheels for every build (or at least for every merged PR).

Part of the pain we're feeling now is technical debt caused by a low release cadence.

**Comment by piskvorky** [comment]
Sure, why not. But please finish this beta release first, to avoid any more mishaps. The current frozen-in-mid-release project state is an invitation to further git trouble (not to mention user confusion).

**Comment by mpenkov** [comment]
I've worked around the problem by removing annoy from the build environment.
